// src/components/Timeline/Ruler.vue
<script setup lang="ts">
import { ref, watch, onBeforeUnmount, onMounted } from 'vue'
import { useCssVar } from '@vueuse/core'
import { RULER_MAP, px2us, us2FrameTime } from '@/utils'
import { useInteractiveStore, InteractiveStore } from "@/store/interactive"
const interactiveStore: InteractiveStore = useInteractiveStore()

const canvas = ref<HTMLCanvasElement|null>(null)
const color = useCssVar('--textColorBase', document.body)
function draw() {
  const containerEl:HTMLDivElement|null = document.querySelector('.track-container')
  if (!canvas.value || !containerEl) return
  const { STEP, TIME, GROUP } = RULER_MAP[interactiveStore.level]
  const { offsetWidth, offsetHeight } = canvas.value
  canvas.value.width = offsetWidth
  canvas.value.height = offsetHeight
  const ctx = canvas.value.getContext('2d')
  if (!ctx) return
  let x = -containerEl.scrollLeft % STEP
  ctx.beginPath()
  ctx.strokeStyle = color.value
  ctx.fillStyle = color.value
  ctx.font = '14px monospace'
  while (x < offsetWidth) {
    const isGroup = ((x + containerEl.scrollLeft) / STEP) % GROUP === 0
    ctx.moveTo(x, offsetHeight / (isGroup ? 1.8 : 1.2))
    ctx.lineTo(x, offsetHeight)
    if (isGroup) {
      const text = us2FrameTime(px2us(x + containerEl.scrollLeft))
      ctx.fillText(text, x - 39, 15)
    }
    x += STEP
  }
  ctx.closePath()
  ctx.stroke()
}

onBeforeUnmount(() => {
  const el:HTMLDivElement|null = document.querySelector('.track-container')
  el?.removeEventListener('scroll', draw)
  window.removeEventListener('resize', draw)
})
onMounted(() => {
  const el:HTMLDivElement|null = document.querySelector('.track-container')
  el?.addEventListener('scroll', draw)
  window.addEventListener('resize', draw)
  draw()
})
watch(interactiveStore, () => draw())

</script>

<template>
  <canvas ref="canvas" />
</template>

<style scoped lang="scss">
canvas {
  grid-area: ruler;
  width: 100%;
  height: 100%;
}
</style>

// src/components/Timeline/Ruler.tsx
import React from 'react'
import { Group, Line, Text, Shape } from 'react-konva'
import Konva from 'konva'
import { RULER_MAP } from '../../const'
import { us2FrameTime, px2us } from '../../utils'

interface RulerProps {
  x?: number
  y?: number
  width: number
  height?: number
  level?: number
  scrollX?: number
}

export default function Ruler({
  x = 0,
  y = 0,
  width,
  height = 15,
  level = 3,
  scrollX = 0,
}: RulerProps) {
  const { STEP, TIME, GROUP } = RULER_MAP[level]
  const sceneFunc = (context: Konva.Context, shape: Konva.Shape) => {
    context.beginPath()
    context._context.font = "13px bold"
    context._context.fillStyle = "rgba(255, 255, 255, 0.5)"
    // 先画底边线
    context.moveTo(x, y + height)
    context.lineTo(width, y + height)
    let posX = x + ~~(scrollX / STEP) * STEP
    while (posX - scrollX < width) {
      context.moveTo(posX - scrollX, y + height)
      const isHigh = (posX - x) / STEP % GROUP === 0
      if (isHigh) {
        context.lineTo(posX - scrollX, y)
        const us = px2us(scrollX + posX - scrollX, level)
        context.fillText(us2FrameTime(us), posX - 35 - scrollX, y - 10)
      } else {
        context.lineTo(posX - scrollX, y + height / 2)
      }
      posX += STEP
    }
    context.closePath()
    context.fillStrokeShape(shape)
  }
  return (
    <Group x={x} y={y}>
      <Shape
        stroke="rgba(255, 255, 255, 0.5)"
        sceneFunc={sceneFunc}
        strokeWidth={1}
        y={y + 30}
        x={0}
      />
    </Group>
  )
}
